"""initial schema

Revision ID: bb8d47a8d7f2
Revises:
Create Date: 2026-07-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb8d47a8d7f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'retired', 'planned', name='pc_status'), nullable=False),
    sa.Column('qr_code', sa.String(length=36), nullable=False),
    sa.Column('build_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_pcs_name'), 'pcs', ['name'], unique=False)
    op.create_table('planned_builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pc_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('mac_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pc_id')
    )
    op.create_table('parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pc_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('cpu', 'gpu', 'ram', 'psu', 'case', 'cooler', 'ssd', 'hdd', 'mobo', 'fan', 'other', name='part_type'), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'faulty', 'rma', 'retired', name='part_condition'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_pc_id'), 'parts', ['pc_id'], unique=False)
    op.create_index(op.f('ix_parts_type'), 'parts', ['type'], unique=False)
    op.create_table('planned_build_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('external_name', sa.String(length=160), nullable=True),
    sa.Column('external_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['planned_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('from_pc_id', sa.String(length=36), nullable=True),
    sa.Column('to_pc_id', sa.String(length=36), nullable=True),
    sa.Column('moved_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['from_pc_id'], ['pcs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_pc_id'], ['pcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_logs_part_id'), 'transfer_logs', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_logs_part_id'), table_name='transfer_logs')
    op.drop_table('transfer_logs')
    op.drop_table('planned_build_items')
    op.drop_index(op.f('ix_parts_type'), table_name='parts')
    op.drop_index(op.f('ix_parts_pc_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_table('network_info')
    op.drop_table('planned_builds')
    op.drop_index(op.f('ix_pcs_name'), table_name='pcs')
    op.drop_table('pcs')
    # ### end Alembic commands ###
