"""add external_type to planned_build_items

Revision ID: e204c45f42a1
Revises: bb8d47a8d7f2
Create Date: 2026-07-02 22:29:55.338826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e204c45f42a1'
down_revision: Union[str, None] = 'bb8d47a8d7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_build_items', sa.Column('external_type', sa.Enum('cpu', 'gpu', 'ram', 'psu', 'case', 'cooler', 'ssd', 'hdd', 'mobo', 'fan', 'other', name='part_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_build_items', 'external_type')
    # ### end Alembic commands ###
